[package]
name = "nazo-oauth-server-object-store"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
chrono.workspace = true
futures-util.workspace = true
nazo-identity.workspace = true
nazo-oauth-server.workspace = true
rust-s3 = { version = "0.37.2", default-features = false, features = ["tokio-rustls-tls"] }
sha2.workspace = true

[dev-dependencies]
base64.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
uuid = { workspace = true, features = ["v7"] }
reqwest = { version = "0.12.28", default-features = false, features = ["multipart", "rustls-tls"] }

[lints]
workspace = true
